import type { Category } from "../types";

export const SEED_CATEGORIES: Category[] = [
  // ── Expense Categories ──────────────────────────────
  { id: "rent",           name: "Rent",               type: "expense" },
  { id: "subscription",   name: "Subscription",       type: "expense" },
  { id: "loan",           name: "Loan",               type: "expense" },
  { id: "amazon",         name: "Amazon",             type: "expense" },
  { id: "ubereats",       name: "Uber Eats",          type: "expense" },
  { id: "grocery",        name: "Grocery",            type: "expense" },
  { id: "restaurants",    name: "Restaurants",        type: "expense" },
  { id: "carparking",     name: "Car Parking",        type: "expense" },
  { id: "petrol",         name: "Petrol",             type: "expense" },
  { id: "officesupplies", name: "Office Supplies",    type: "expense" },
  { id: "insurance",      name: "Insurance",          type: "expense" },
  { id: "hydro",          name: "Hydro",              type: "expense" },
  { id: "health",         name: "Health",             type: "expense" },
  { id: "mobile",         name: "Mobile",             type: "expense" },
  { id: "homesupport",    name: "Home Support",       type: "expense" },
  { id: "internet",       name: "Internet",           type: "expense" },
  { id: "highway401",     name: "401 Highway",        type: "expense" },
  { id: "other",          name: "Other",              type: "expense" },
  { id: "shopping",       name: "Shopping",           type: "expense" },
  { id: "trip",           name: "Trip",               type: "expense" },
  { id: "charity",        name: "Charity",            type: "expense" },
  { id: "carservice",     name: "Car Service",        type: "expense" },
  { id: "sports",         name: "Sports",             type: "expense" },
  { id: "tax",            name: "Tax",                type: "expense" },
  { id: "auctions",       name: "Auctions",           type: "expense" },
  { id: "savings",        name: "Savings",            type: "expense" },
  { id: "beauty",         name: "Beauty",             type: "expense" },
  { id: "timhortens",     name: "Tim Hortens",        type: "expense" },
  { id: "rrsp",           name: "RRSP",               type: "expense" },
  { id: "tsfa",           name: "TSFA",               type: "expense" },
  { id: "fhsa",           name: "FHSA",               type: "expense" },
  { id: "iphone",         name: "Iphone",             type: "expense" },
  { id: "entertainment",  name: "Entertainment",      type: "expense" },
  // ── Income Categories ───────────────────────────────
  { id: "salary",         name: "Salary",             type: "income" },
  { id: "carboncrebate",  name: "Canada Carbon Rebate", type: "income" },
  { id: "carryfwd",       name: "Carry Fwd",          type: "income" },
];
